name: sat_scraping
description: Herramienta que permite obtener informaciÃ³n fiscal de un contribuyente. Ayuda a automatizar dicho proceso y puede ser utilizado en aplicaciones de negocios o financieras.
version: 0.0.6
homepage: https://github.com/OscarTinajero117/sat_scraping
issues: https://github.com/OscarTinajero117/sat_scraping/issues

environment:
  sdk: ">=2.19.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  beautiful_soup_dart: ^0.3.0
  flutter:
    sdk: flutter
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
